# Autolab - autograding docker image

FROM ubuntu:18.04
MAINTAINER Autolab Team <autolab-dev@andrew.cmu.edu>

RUN apt-get update && apt-get install -y \
  build-essential \
  gcc \
  git \
  make \
  sudo \
  && rm -rf /var/lib/apt/lists/*

# Install autodriver
WORKDIR /home
RUN useradd autolab
RUN useradd autograde
RUN mkdir autolab autograde output
RUN chown autolab:autolab autolab
RUN chown autolab:autolab output
RUN chown autograde:autograde autograde
RUN git clone --depth 1 https://github.com/autolab/Tango.git
WORKDIR Tango/autodriver
RUN make clean && make
RUN cp autodriver /usr/bin/autodriver
RUN chmod +s /usr/bin/autodriver

# Clean up
WORKDIR /home
RUN apt-get remove -y git && apt-get -y autoremove && rm -rf Tango/

# Check installation
RUN ls -l /home
RUN which autodriver


# Newly Added #
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential wget ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Install OpenCilk into /opt/opencilk
RUN mkdir -p /opt/opencilk && \
    wget https://github.com/OpenCilk/opencilk-project/releases/download/opencilk/v2.1/opencilk-2.1.0-aarch64-linux-gnu-ubuntu-22.04.sh -O /tmp/opencilk.sh && \
    sh /tmp/opencilk.sh --prefix=/opt/opencilk --exclude-subdir && \
    rm /tmp/opencilk.sh

# Put OpenCilk's clang/clang++ first on PATH for all users
ENV PATH=/opt/opencilk/bin:${PATH}
